### ISSUE TITLE
可以改为不需要继承的吗？

### ISSUE THREAD

**Issue by ArthurCL** [fanrongQu/FRNavigationController#1]
有些第三方功能需要继承，oc不支持多继承，就冲突了，两者不能兼容，我从pod下载的一些类库，实现某些功能的时候，需要用到继承

**Comment by fanrongQu** [comment]
你要实现什么功能呢？导航控制器由于自定义了backButtonItem，需要实现back功能。若果你需要拓展其他复杂功能，可以直接下载源文件实现个性化功能

**Comment by fanrongQu** [comment]
如果是其他功能点，请提供你的需求。我看下能够做兼容处理不

**Comment by ArthurCL** [comment]
backButtonItem可以用leftBarButtonItem代替吧？      直接用UIBarButtonItem+FRAdd里的方法创建一个item，我项目中用的LBXScan实现的扫描二维码功能，就需要用到继承

**Comment by fanrongQu** [comment]
嗯嗯，那样你需要自己写一下这个方法。既然这样没你可以直接把源码下载下来，然后把你需要的分类拖到项目里就可以了。
1、NSObject+FRRuntime  运行时分类
2、UINavigationItem+FRFixSpace 适配iOS 11调整间距，需要1的支持
3、UINavigationController+FDFullscreenPopGesture滑动返回手势。
4、UIBarButtonItem+FRAdd  BarButtonItem快速创建分类
希望能够帮助到你，觉得不错的话请✨✨✨
